### ISSUE TITLE
AND gate

### ISSUE THREAD

**Issue by bsiegelwax** [QuEraComputing/UnitDiskMapping.jl#44]
The AND gate is too short as drawn and generates a y spacing error. The simulator doesn't catch it, but Aquila does.

![neutral atom Toffoli](https://user-images.githubusercontent.com/70060202/217030389-aa0e0209-39ad-4b60-b13f-4323e470d88a.png)

![4 post-processed](https://user-images.githubusercontent.com/70060202/217030318-19e02a9c-4fc4-42a9-8e48-dff2848a0b9c.png)

[notebooks](https://github.com/QuEraComputing/UnitDiskMapping.jl/tree/main/notebooks)/tutorial.jl

**Comment by GiggleLiu** [comment]
Hi thanks for the issue. I did not get it, do you have any suggested change?

**Comment by bsiegelwax** [comment]
The node between x1 and y1 has to be farther from y1 or it's easy to get a y spacing error on Aquila.

**Comment by GiggleLiu** [comment]
Sorry, I am not familiar with the spacing error on Aquila. Is there anything I can help to fix this issue?

**Comment by bsiegelwax** [comment]
That's why I opened an issue. The AND gate, as described in UnitDiskMapping.jl, generates a y spacing error if actually run on Aquila.

**Comment by bsiegelwax** [comment]
I'm using QuEra's MIS code. But, when you arrange the atoms as shown, you may get a y spacing error. I did. I resolved it by increasing the y spacing.
